# "version" is version of the docker-compose.yml format
version: "3"

services:
  production_db:
    image: postgres:14.8
    container_name: production
    ports:
      - 1234:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: netbank
    volumes:
      - ./script:/docker-entrypoint-initdb.d
      - db-store-production:/var/lib/postgresql/data

  test_db:
    image: postgres:14.8
    container_name: test
    ports:
      - 5180:5432
    environment:
      POSTGRES_USER: testUser
      POSTGRES_PASSWORD: testPassword
      POSTGRES_DB: netbank_test
    volumes:
      - ./script:/docker-entrypoint-initdb.d
      - db-store-test:/var/lib/postgresql/data

volumes:
  db-store-production:
  db-store-test:
