# "version" is version of the docker-compose.yml format
version: "3"

services:
  db:
    image: postgres:14.8
    container_name: netbank_db
    ports:
      - 1234:1234
    volumes:
      - db-store:/var/lib/postgresql/data
      - ./script:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=passw0rd
volumes:
  db-store:
